name: chart-lint

on:
  push:
    branches: [main]
    paths:
      - "charts/**"
      - ".github/workflows/chart-lint.yaml"
      - ".github/ct.yaml"
      - "Makefile"
  pull_request:
    branches: [main]
    paths:
      - "charts/**"
      - ".github/workflows/chart-lint.yaml"
      - ".github/ct.yaml"
      - "Makefile"
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing lint
        run: ct lint --config .github/ct.yaml

      - name: Install helm-unittest plugin
        run: make helm-unittest-plugin

      - name: Run helm-unittest
        run: make helm-test CHART=charts/iamra-injector
